export const GET_COURSES_RESPONSE = 'GET_COURSES_RESPONSE';
export const GET_COURSE_RESPONSE = 'GET_COURSE_RESPONSE';
export const ADD_NEW_COURSE_RESPONSE = 'ADD_NEW_COURSE_RESPONSE';
export const UPDATE_EXISTING_COURSE_RESPONSE = 'UPDATE_EXISTING_COURSE_RESPONSE';
export const DELETE_COURSE_RESPONSE = 'DELETE_COURSE_RESPONSE';

export const GET_AUTHORS_RESPONSE = 'GET_AUTHORS_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';


export const GET_SHIPMENTS_RESPONSE = 'GET_SHIPMENTS_RESPONSE';
export const GET_SHIPMENT_RESPONSE = 'GET_SHIPMENTRESPONSE';
export const ADD_NEW_SHIPMENT_RESPONSE = 'ADD_NEW_SHIPMENT_RESPONSE';
export const UPDATE_EXISTING_SHIPMENT_RESPONSE = 'UPDATE_EXISTING_SHIPMENT_RESPONSE';
export const DELETE_SHIPMENT_RESPONSE = 'DELETE_SHIPMENT_RESPONSE';
